TRANSLATIONS = {
    "EN": {
        "app_title": "🛡️ Shield AML: NiceGUI Edition",
        "tab_dashboard": "Dashboard",
        "tab_simulation": "Simulation",
        "tab_history": "History",
        "tab_settings": "Settings",
        "lbl_sender": "Sender ID",
        "lbl_receiver": "Receiver ID",
        "lbl_amount": "Amount (USD)",
        "lbl_time": "Transaction Time (HH:MM)",
        "lbl_segment": "Customer Segment",
        "lbl_intl": "International Transaction?",
        "btn_analyze": "⚡ Analyze Transaction",
        "btn_add_seg": "Add Segment",
        "btn_del_seg": "Delete Segment",
        "lbl_maint": "Maintenance Mode",
        "lbl_lang": "Language",
        "res_approved": "✅ APPROVED",
        "res_monitor": "⚠️ MONITORING REQUIRED",
        "res_reject": "🚨 REJECTED",
        "msg_maint": "System is currently in maintenance mode. Inputs disabled.",
        "hist_date": "Timestamp",
        "hist_sender": "Sender",
        "hist_amount": "Amount",
        "hist_risk": "Risk Score",
        "hist_status": "Status",
        "rule_hard": "HARD RULE: Global Cap Exceeded (>10M)",
        "rule_black": "BLACKLIST: User ID Match",
        "rule_ai": "AI Risk Assessment",
        "rule_seg_limit": "RULE: Segment Amount Limit Exceeded",
        "rule_freq": "RULE: Transaction Frequency Limit Exceeded",
        "rule_hist": "RULE: Significant Deviation from History",
        "rule_night_limit": "RULE: Night Time High Value (Near Limit)",
        "rule_watch": "WATCHLIST: Entity on Watchlist",
        "rule_ai_reject": "AI: High Fraud Probability",
        "rule_ai_monitor": "AI: Anomaly Detected",
        "rule_ai_safe": "AI: Normal Behavior",
        "stat_daily": "Daily Volume",
        "stat_suspicious": "Suspicious (Total)",
        "stat_suspicious_recent": "Recent Suspicious Activity",
        "stat_monitor": "Pending Review",
        "stat_monitor_recent": "Recent Pending Reviews",
        "stat_queued": "Queued (Maintenance)",
        "lbl_global_cap": "Global Transaction Cap (USD)",
        "lbl_reason": "Reason",
        "lbl_added_on": "Added On",
        "btn_delete": "Delete",
        "cfg_night_start": "Night Start Hour (0-23)",
        "cfg_night_end": "Night End Hour (0-23)",
        "cfg_night_ratio": "Night Limit Ratio (0.0-1.0)",
        "cfg_hist_mult": "History Deviation Multiplier (x)",
        "btn_refresh": "Refresh Data",
        "filter_status": "Filter by Status",
        "hdr_global_config": "Global Configuration",
        "hdr_adv_rules": "Advanced Rules Parameters",
        "hdr_segment_rules": "Segment Rules Configuration",
        "hdr_restricted_lists": "Restricted Lists Management",
        "hdr_system_controls": "System Controls",
        "lbl_actions": "Actions",
        "nav_title": "Navigation",
        "lbl_manual_entry": "Manual Transaction Entry",
        "btn_queue": "Queue Transaction",
        "lbl_select_seg_edit": "Select Segment to Edit",
        "lbl_min_amt": "Min Amount",
        "lbl_max_amt": "Max Amount",
        "lbl_daily_lim": "Daily Txn Limit",
        "lbl_monthly_lim": "Monthly Txn Limit",
        "btn_save_rules": "Save Rules",
        "lbl_new_seg_name": "New Segment Name",
        "lbl_select_seg_del": "Select Segment to Delete",
        "btn_process_queue": "Process Queued Transactions",
        "btn_update_cap": "Update Cap",
        "btn_save_adv": "Save Advanced Rules",
        "btn_close": "Close",
        "dlg_action_title": "Transaction Action",
        "err_comment_req": "Reason is required",
        "btn_approve": "Approve",
        "btn_reject": "Reject",
        "msg_trans_approved": "Transaction Approved",
        "msg_trans_rejected": "Transaction Rejected",
        "stat_queued_pending": "Pending Processing",
        "err_time_fmt": "Invalid Time Format. Use HH:MM",
        "msg_queued": "Transaction Queued",
        "tab_blacklist": "Blacklist",
        "tab_watchlist": "Watchlist",
        "lbl_entity_id": "Entity ID",
        "msg_added_to": "Added to",
        "msg_removed": "Removed",
        "msg_no_queue": "No queued transactions",
        "msg_processed_queue": "Processed {count} transactions"
    },
    "TR": {
        "app_title": "🛡️ Shield AML Operasyon",
        "tab_dashboard": "Panel",
        "tab_simulation": "Simülasyon",
        "tab_history": "Geçmiş",
        "tab_settings": "Ayarlar",
        "lbl_sender": "Gönderici ID",
        "lbl_receiver": "Alıcı ID",
        "lbl_amount": "Tutar (USD)",
        "lbl_time": "İşlem Saati (SS:DD)",
        "lbl_segment": "Müşteri Segmenti",
        "lbl_intl": "Uluslararası İşlem?",
        "btn_analyze": "⚡ İşlemi Analiz Et",
        "btn_add_seg": "Segment Ekle",
        "btn_del_seg": "Segment Sil",
        "lbl_maint": "Bakım Modu",
        "lbl_lang": "Dil",
        "res_approved": "✅ ONAYLANDI",
        "res_monitor": "⚠️ İZLEME GEREKLİ",
        "res_reject": "🚨 REDDEDİLDİ",
        "msg_maint": "Sistem şu anda bakım modunda. Girişler devre dışı.",
        "hist_date": "Zaman Damgası",
        "hist_sender": "Gönderici",
        "hist_amount": "Tutar",
        "hist_risk": "Risk Skoru",
        "hist_status": "Durum",
        "rule_hard": "SERT KURAL: Global Limit Aşıldı (>10M)",
        "rule_black": "KARA LİSTE: Kullanıcı Eşleşmesi",
        "rule_ai": "Yapay Zeka Risk Değerlendirmesi",
        "rule_seg_limit": "KURAL: Segment Tutar Limiti Aşıldı",
        "rule_freq": "KURAL: İşlem Sıklık Limiti Aşıldı",
        "rule_hist": "KURAL: Geçmiş Ortalamadan Aşırı Sapma",
        "rule_night_limit": "KURAL: Gece Saati Yüksek Tutar (Limite Yakın)",
        "rule_watch": "İZLEME LİSTESİ: Varlık İzleme Listesinde",
        "rule_ai_reject": "YZ: Yüksek Dolandırıcılık İhtimali",
        "rule_ai_monitor": "YZ: Anormallik Tespit Edildi",
        "rule_ai_safe": "YZ: Normal Davranış",
        "stat_daily": "Günlük Hacim",
        "stat_suspicious": "Şüpheli (Toplam)",
        "stat_suspicious_recent": "Son Şüpheli İşlemler",
        "stat_monitor": "İnceleme Bekleyen",
        "stat_monitor_recent": "İnceleme Bekleyen Son İşlemler",
        "stat_queued": "Kuyrukta (Bakım)",
        "lbl_global_cap": "Global İşlem Limiti (USD)",
        "lbl_reason": "Sebep",
        "lbl_added_on": "Eklenme Tarihi",
        "btn_delete": "Sil",
        "cfg_night_start": "Gece Başlangıç Saati (0-23)",
        "cfg_night_end": "Gece Bitiş Saati (0-23)",
        "cfg_night_ratio": "Gece Limit Oranı (0.0-1.0)",
        "cfg_hist_mult": "Geçmiş Sapma Çarpanı (x)",
        "btn_refresh": "Verileri Yenile",
        "filter_status": "Duruma Göre Filtrele",
        "hdr_global_config": "Global Yapılandırma",
        "hdr_adv_rules": "Gelişmiş Kural Parametreleri",
        "hdr_segment_rules": "Segment Kural Yapılandırması",
        "hdr_restricted_lists": "Kısıtlı Liste Yönetimi",
        "hdr_system_controls": "Sistem Kontrolleri",
        "lbl_actions": "İşlemler",
        "nav_title": "Navigasyon",
        "lbl_manual_entry": "Manuel İşlem Girişi",
        "btn_queue": "İşlemi Kuyruğa Al",
        "lbl_select_seg_edit": "Düzenlenecek Segmenti Seç",
        "lbl_min_amt": "Min Tutar",
        "lbl_max_amt": "Maks Tutar",
        "lbl_daily_lim": "Günlük İşlem Limiti",
        "lbl_monthly_lim": "Aylık İşlem Limiti",
        "btn_save_rules": "Kuralları Kaydet",
        "lbl_new_seg_name": "Yeni Segment Adı",
        "lbl_select_seg_del": "Silinecek Segmenti Seç",
        "btn_process_queue": "Kuyruktaki İşlemleri İşle",
        "btn_update_cap": "Limiti Güncelle",
        "btn_save_adv": "Gelişmiş Kuralları Kaydet",
        "btn_close": "Kapat",
        "dlg_action_title": "İşlem Aksiyonu",
        "err_comment_req": "Sebep girilmesi zorunludur",
        "btn_approve": "Onayla",
        "btn_reject": "Reddet",
        "msg_trans_approved": "İşlem Onaylandı",
        "msg_trans_rejected": "İşlem Reddedildi",
        "stat_queued_pending": "İşlem Bekliyor",
        "err_time_fmt": "Geçersiz Saat Formatı. SS:DD kullanın",
        "msg_queued": "İşlem Kuyruğa Alındı",
        "tab_blacklist": "Kara Liste",
        "tab_watchlist": "İzleme Listesi",
        "lbl_entity_id": "Kimlik ID",
        "msg_added_to": "Eklendi:",
        "msg_removed": "Kaldırıldı:",
        "msg_no_queue": "Kuyrukta işlem yok",
        "msg_processed_queue": "{count} işlem işlendi"
    }
}
